name: Generate M3U File Jio Zee

on:
  workflow_dispatch:
  push:
    paths:
      - 'jio_z_m3u_extra_fields.py'
      - 'full_channels.json'

jobs:
  generate-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run script to generate M3U
        run: |
          python jio_z_m3u_extra_fields.py

      - name: Upload generated M3U file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: new_full_jio_zee.m3u
          path: new_full_jio_zee.m3u

      - name: Commit and push changes
        run: |
          git add new_full_jio_zee.m3u  # Añadir el nuevo nombre del archivo M3U

          git commit -m "Update new_full_jio_zee.m3u file" || echo "No changes to commit" 
          git push origin HEAD:main  # Cambia  main` si utilizas otra rama 
